version: '3.8'

services:
  postgres:
    image: postgres:17  # PostgreSQL version 17
    container_name: securehome_postgres
    environment:
      POSTGRES_USER: muteeb
      POSTGRES_PASSWORD: muteeb123
      POSTGRES_DB: securehome_db
    ports:
      - "5433:5432"  # Mapping host port 5433 to container port 5432
    volumes:
      - postgres_data:/var/lib/postgresql/data  # Persistent data storage
    restart: always  # Ensure the container restarts automatically

volumes:
  postgres_data:
    driver: local
